# Assignment No. 14

Name:Rushabh Ratnaparkhi

College:Your College Name

Branch:Computer Engineering

Domain:AIML

GitHub Repository:

In [1]:
#Q1
import numpy as np

arr = np.random.randint(10, 101, (5, 6))

print("2D Array:")
print(arr)

# Print Shape
print("\nShape:", arr.shape)

# Print Total Number of Elements
print("Size:", arr.size)

# Print Data Type
print("Data Type:", arr.dtype)

2D Array:
[[ 33  75  69  57  99  96]
 [ 37  64  25  10 100  43]
 [ 41  35  55  36  93  71]
 [ 30  63  81  93  63  80]
 [ 36  51  16  43  16  82]]

Shape: (5, 6)
Size: 30
Data Type: int32


In [2]:
#Q2
import numpy as np
arr = np.random.randint(1, 51, 20)

print("Array:")
print(arr)

# Minimum value and index
print("\nMinimum Value:", np.min(arr))
print("Index of Minimum Value:", np.argmin(arr))

# Maximum value and index
print("\nMaximum Value:", np.max(arr))
print("Index of Maximum Value:", np.argmax(arr))

# Sum
print("\nSum:", np.sum(arr))

# Mean
print("Mean:", np.mean(arr))

# Standard Deviation
print("Standard Deviation:", np.std(arr))

Array:
[ 1 12 19 19 39 45  9  3 37 47 47 14  6 48  2 38 42 32 31 41]

Minimum Value: 1
Index of Minimum Value: 0

Maximum Value: 48
Index of Maximum Value: 13

Sum: 532
Mean: 26.6
Standard Deviation: 16.66253282067285


In [ ]:
#Q3
