# Assignment No. 14

Name:Rushabh Ratnaparkhi

College:Your College Name

Branch:Computer Engineering

Domain:AIML

GitHub Repository:

In [1]:
#Q1
import numpy as np

arr = np.random.randint(10, 101, (5, 6))

print("2D Array:")
print(arr)

# Print Shape
print("\nShape:", arr.shape)

# Print Total Number of Elements
print("Size:", arr.size)

# Print Data Type
print("Data Type:", arr.dtype)

2D Array:
[[ 33  75  69  57  99  96]
 [ 37  64  25  10 100  43]
 [ 41  35  55  36  93  71]
 [ 30  63  81  93  63  80]
 [ 36  51  16  43  16  82]]

Shape: (5, 6)
Size: 30
Data Type: int32


In [2]:
#Q2
import numpy as np
arr = np.random.randint(1, 51, 20)

print("Array:")
print(arr)

# Minimum value and index
print("\nMinimum Value:", np.min(arr))
print("Index of Minimum Value:", np.argmin(arr))

# Maximum value and index
print("\nMaximum Value:", np.max(arr))
print("Index of Maximum Value:", np.argmax(arr))

# Sum
print("\nSum:", np.sum(arr))

# Mean
print("Mean:", np.mean(arr))

# Standard Deviation
print("Standard Deviation:", np.std(arr))

Array:
[ 1 12 19 19 39 45  9  3 37 47 47 14  6 48  2 38 42 32 31 41]

Minimum Value: 1
Index of Minimum Value: 0

Maximum Value: 48
Index of Maximum Value: 13

Sum: 532
Mean: 26.6
Standard Deviation: 16.66253282067285


In [3]:
#Q3
import numpy as np
# Create a 4x5 matrix of random integers
matrix = np.random.randint(20, 81, (4, 5))

print("Matrix:")
print(matrix)

# Entire Matrix Statistics
print("\nMinimum Value:", np.min(matrix))
print("Maximum Value:", np.max(matrix))

print("Sum:", np.sum(matrix))

print("Mean:", np.mean(matrix))

print("Standard Deviation:", np.std(matrix))

# Sum of each row
print("\nRow-wise Sum:")
print(np.sum(matrix, axis=1))

# Sum of each column
print("\nColumn-wise Sum:")
print(np.sum(matrix, axis=0))

Matrix:
[[66 66 34 21 56]
 [62 66 23 44 62]
 [56 31 24 25 55]
 [75 59 58 24 41]]

Minimum Value: 21
Maximum Value: 75
Sum: 948
Mean: 47.4
Standard Deviation: 17.41952927033334

Row-wise Sum:
[243 257 191 257]

Column-wise Sum:
[259 222 139 114 214]


In [4]:
#Q4
import numpy as np
# Create array from 1 to 24
arr = np.arange(1, 25)

print("Original Array:")
print(arr)

# Reshape into (4,6)
array1 = arr.reshape(4, 6)

print("\nReshape (4,6):")
print(array1)
print("Shape:", array1.shape)

# Reshape into (3,8)
array2 = arr.reshape(3, 8)

print("\nReshape (3,8):")
print(array2)
print("Shape:", array2.shape)

# Reshape into (2,3,4)
array3 = arr.reshape(2, 3, 4)

print("\nReshape (2,3,4):")
print(array3)
print("Shape:", array3.shape)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Reshape (4,6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

Reshape (3,8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape: (3, 8)

Reshape (2,3,4):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


In [5]:
#Q5
import numpy as np

# Create the given array
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print("Original Array:")
print(arr)

# first row
print("\nFirst Row:")
print(arr[0])

# last column
print("\nLast Column:")
print(arr[:, -1])

# center 2x2 submatrix
print("\nCenter 2x2 Submatrix:")
print(arr[1:3, 1:3])

# all even numbers using boolean indexing
print("\nEven Numbers:")
print(arr[arr % 2 == 0])

Original Array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

First Row:
[10 20 30 40]

Last Column:
[ 40  80 120]

Center 2x2 Submatrix:
[[ 60  70]
 [100 110]]

Even Numbers:
[ 10  20  30  40  50  60  70  80  90 100 110 120]


In [6]:
#Q6
import numpy as np

arr = np.random.randint(1, 101, (5, 5))

print("Original Matrix:")
print(arr)

# Print diagonal elements
print("\nDiagonal Elements:")
print(np.diagonal(arr))

# Print elements greater than 50
print("\nElements Greater Than 50:")
print(arr[arr > 50])

# Replace all elements less than 30 with 0
arr[arr < 30] = 0

# Print modified array
print("\nModified Matrix:")
print(arr)

Original Matrix:
[[ 99  87  35  50  39]
 [ 96  27  93  93   6]
 [ 17  22  89  85  67]
 [ 44   6  46  92  77]
 [100  72  28  33  23]]

Diagonal Elements:
[99 27 89 92 23]

Elements Greater Than 50:
[ 99  87  96  93  93  89  85  67  92  77 100  72]

Modified Matrix:
[[ 99  87  35  50  39]
 [ 96   0  93  93   0]
 [  0   0  89  85  67]
 [ 44   0  46  92  77]
 [100  72   0  33   0]]


In [7]:
#Q7
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

# Addition
print("Addition:")
print(a + b)

# Subtraction
print("\nSubtraction:")
print(a - b)

# Multiplication
print("\nMultiplication:")
print(a * b)

# Division
print("\nDivision:")
print(a / b)

# Element-wise Power
print("\nElement-wise Power:")
print(a ** b)

# Modulo Operation
print("\nModulo Operation:")
print(a % b)

Addition:
[11 22 33 44]

Subtraction:
[ 9 18 27 36]

Multiplication:
[ 10  40  90 160]

Division:
[10. 10. 10. 10.]

Element-wise Power:
[     10     400   27000 2560000]

Modulo Operation:
[0 0 0 0]
