# Assignment No. 14

Name:Rushabh Ratnaparkhi

College:J.T.MAHAJAN POLYTECHNIC, FAIZPUR

Branch:Computer Engineering

Domain:AIML

GitHub Repository: https://github.com/rushabh161/assignment14

In [1]:
#Q1
import numpy as np

arr = np.random.randint(10, 101, (5, 6))

print("2D Array:")
print(arr)

# Print Shape
print("\nShape:", arr.shape)

# Print Total Number of Elements
print("Size:", arr.size)

# Print Data Type
print("Data Type:", arr.dtype)

2D Array:
[[ 33  75  69  57  99  96]
 [ 37  64  25  10 100  43]
 [ 41  35  55  36  93  71]
 [ 30  63  81  93  63  80]
 [ 36  51  16  43  16  82]]

Shape: (5, 6)
Size: 30
Data Type: int32


In [2]:
#Q2
import numpy as np
arr = np.random.randint(1, 51, 20)

print("Array:")
print(arr)

# Minimum value and index
print("\nMinimum Value:", np.min(arr))
print("Index of Minimum Value:", np.argmin(arr))

# Maximum value and index
print("\nMaximum Value:", np.max(arr))
print("Index of Maximum Value:", np.argmax(arr))

# Sum
print("\nSum:", np.sum(arr))

# Mean
print("Mean:", np.mean(arr))

# Standard Deviation
print("Standard Deviation:", np.std(arr))

Array:
[ 1 12 19 19 39 45  9  3 37 47 47 14  6 48  2 38 42 32 31 41]

Minimum Value: 1
Index of Minimum Value: 0

Maximum Value: 48
Index of Maximum Value: 13

Sum: 532
Mean: 26.6
Standard Deviation: 16.66253282067285


In [3]:
#Q3
import numpy as np
# Create a 4x5 matrix of random integers
matrix = np.random.randint(20, 81, (4, 5))

print("Matrix:")
print(matrix)

# Entire Matrix Statistics
print("\nMinimum Value:", np.min(matrix))
print("Maximum Value:", np.max(matrix))

print("Sum:", np.sum(matrix))

print("Mean:", np.mean(matrix))

print("Standard Deviation:", np.std(matrix))

# Sum of each row
print("\nRow-wise Sum:")
print(np.sum(matrix, axis=1))

# Sum of each column
print("\nColumn-wise Sum:")
print(np.sum(matrix, axis=0))

Matrix:
[[66 66 34 21 56]
 [62 66 23 44 62]
 [56 31 24 25 55]
 [75 59 58 24 41]]

Minimum Value: 21
Maximum Value: 75
Sum: 948
Mean: 47.4
Standard Deviation: 17.41952927033334

Row-wise Sum:
[243 257 191 257]

Column-wise Sum:
[259 222 139 114 214]


In [4]:
#Q4
import numpy as np
# Create array from 1 to 24
arr = np.arange(1, 25)

print("Original Array:")
print(arr)

# Reshape into (4,6)
array1 = arr.reshape(4, 6)

print("\nReshape (4,6):")
print(array1)
print("Shape:", array1.shape)

# Reshape into (3,8)
array2 = arr.reshape(3, 8)

print("\nReshape (3,8):")
print(array2)
print("Shape:", array2.shape)

# Reshape into (2,3,4)
array3 = arr.reshape(2, 3, 4)

print("\nReshape (2,3,4):")
print(array3)
print("Shape:", array3.shape)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Reshape (4,6):
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)

Reshape (3,8):
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape: (3, 8)

Reshape (2,3,4):
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)


In [5]:
#Q5
import numpy as np

# Create the given array
arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print("Original Array:")
print(arr)

# first row
print("\nFirst Row:")
print(arr[0])

# last column
print("\nLast Column:")
print(arr[:, -1])

# center 2x2 submatrix
print("\nCenter 2x2 Submatrix:")
print(arr[1:3, 1:3])

# all even numbers using boolean indexing
print("\nEven Numbers:")
print(arr[arr % 2 == 0])

Original Array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

First Row:
[10 20 30 40]

Last Column:
[ 40  80 120]

Center 2x2 Submatrix:
[[ 60  70]
 [100 110]]

Even Numbers:
[ 10  20  30  40  50  60  70  80  90 100 110 120]


In [6]:
#Q6
import numpy as np

arr = np.random.randint(1, 101, (5, 5))

print("Original Matrix:")
print(arr)

# Print diagonal elements
print("\nDiagonal Elements:")
print(np.diagonal(arr))

# Print elements greater than 50
print("\nElements Greater Than 50:")
print(arr[arr > 50])

# Replace all elements less than 30 with 0
arr[arr < 30] = 0

# Print modified array
print("\nModified Matrix:")
print(arr)

Original Matrix:
[[ 99  87  35  50  39]
 [ 96  27  93  93   6]
 [ 17  22  89  85  67]
 [ 44   6  46  92  77]
 [100  72  28  33  23]]

Diagonal Elements:
[99 27 89 92 23]

Elements Greater Than 50:
[ 99  87  96  93  93  89  85  67  92  77 100  72]

Modified Matrix:
[[ 99  87  35  50  39]
 [ 96   0  93  93   0]
 [  0   0  89  85  67]
 [ 44   0  46  92  77]
 [100  72   0  33   0]]


In [7]:
#Q7
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

# Addition
print("Addition:")
print(a + b)

# Subtraction
print("\nSubtraction:")
print(a - b)

# Multiplication
print("\nMultiplication:")
print(a * b)

# Division
print("\nDivision:")
print(a / b)

# Element-wise Power
print("\nElement-wise Power:")
print(a ** b)

# Modulo Operation
print("\nModulo Operation:")
print(a % b)

Addition:
[11 22 33 44]

Subtraction:
[ 9 18 27 36]

Multiplication:
[ 10  40  90 160]

Division:
[10. 10. 10. 10.]

Element-wise Power:
[     10     400   27000 2560000]

Modulo Operation:
[0 0 0 0]


In [10]:
#Q8
import numpy as np

# Create matrices
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])

print("Matrix A:\n", A)
print("Matrix B:\n", B)
# Element-wise Multiplication
print("Element-wise Multiplication:")
print(A * B)

# Matrix Multiplication
print("\nMatrix Multiplication:")
print(A @ B)


# * performs multiplication between corresponding elements.
# @ performs actual matrix multiplication.

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Element-wise Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [11]:
#Q9
import numpy as np

# Generate a 6x6 matrix using random numbers
arr = np.random.randn(6, 6)

print("Original Matrix:")
print(arr)

# Shape
print("\nShape:", arr.shape)

# Size
print("Size:", arr.size)

# Data Type
print("Data Type:", arr.dtype)

# Index of maximum value
max_index = np.unravel_index(np.argmax(arr), arr.shape)
print("\nIndex of Maximum Value:", max_index)

# Index of minimum value
min_index = np.unravel_index(np.argmin(arr), arr.shape)
print("Index of Minimum Value:", min_index)

# Extract top-left 3x3 submatrix
print("\nTop-left 3x3 Submatrix:")
print(arr[:3, :3])

# Replace negative values with absolute values
arr = np.abs(arr)

print("\nModified Matrix:")
print(arr)

# Mean of modified matrix
print("\nMean:", np.mean(arr))

Original Matrix:
[[-0.44377073 -0.22872456  0.51061485 -0.40842218  0.63079714 -0.64536053]
 [-0.15070892  1.31876311 -0.26271889  0.70101004 -0.37643647  0.90316901]
 [-0.97628459 -0.57647032 -0.37878105 -0.32308116 -0.73418877 -0.16125071]
 [ 0.2138762   0.8248046  -2.15178663  0.31319593  0.25601119 -0.95865107]
 [-0.21694815 -0.93150704  0.17656434 -2.18078466 -1.18713709  0.64026815]
 [ 2.13812463 -0.00241351 -1.43159068  2.20839131  0.04308065 -0.2661104 ]]

Shape: (6, 6)
Size: 36
Data Type: float64

Index of Maximum Value: (np.int64(5), np.int64(3))
Index of Minimum Value: (np.int64(4), np.int64(3))

Top-left 3x3 Submatrix:
[[-0.44377073 -0.22872456  0.51061485]
 [-0.15070892  1.31876311 -0.26271889]
 [-0.97628459 -0.57647032 -0.37878105]]

Modified Matrix:
[[0.44377073 0.22872456 0.51061485 0.40842218 0.63079714 0.64536053]
 [0.15070892 1.31876311 0.26271889 0.70101004 0.37643647 0.90316901]
 [0.97628459 0.57647032 0.37878105 0.32308116 0.73418877 0.16125071]
 [0.2138762  0.824

In [12]:
#Q10
# STUDENT PERFORMANCE ANALYSIS
import numpy as np

# Generate random marks for 10 students and 5 subjects
marks = np.random.randint(30, 101, (10, 5))

print("Student Marks:")
print(marks)

# Calculate total marks of each student
total_marks = np.sum(marks, axis=1)

print("\nTotal Marks:")
print(total_marks)

# Calculate average marks of each student
average_marks = np.mean(marks, axis=1)

print("\nAverage Marks:")
print(average_marks)

# Student with highest total marks
highest = np.argmax(total_marks)

print("\nTop Student Index:", highest)

print("Top Student Marks:")
print(marks[highest])

# Student with lowest total marks
lowest = np.argmin(total_marks)

print("\nLowest Student Index:", lowest)

print("Lowest Student Marks:")
print(marks[lowest])

# Overall class mean
print("\nOverall Class Mean:")
print(np.mean(marks))

# Overall class standard deviation
print("\nOverall Class Standard Deviation:")
print(np.std(marks))

# Demonstrate reshape
reshaped = marks.reshape(5, 10)

print("\nReshaped Array (5 x 10):")
print(reshaped)

# Extract marks of top 3 students
top3 = np.argsort(total_marks)[-3:]

print("\nTop 3 Student Indices:")
print(top3)

print("\nMarks of Top 3 Students:")
print(marks[top3])

Student Marks:
[[90 91 77 74 97]
 [77 49 87 49 60]
 [41 62 49 60 75]
 [84 71 77 75 70]
 [44 83 31 84 81]
 [36 50 81 91 52]
 [56 68 30 46 89]
 [84 34 32 31 34]
 [88 80 68 52 63]
 [63 82 37 41 31]]

Total Marks:
[429 322 287 377 323 310 289 215 351 254]

Average Marks:
[85.8 64.4 57.4 75.4 64.6 62.  57.8 43.  70.2 50.8]

Top Student Index: 0
Top Student Marks:
[90 91 77 74 97]

Lowest Student Index: 7
Lowest Student Marks:
[84 34 32 31 34]

Overall Class Mean:
63.14

Overall Class Standard Deviation:
20.20099997524875

Reshaped Array (5 x 10):
[[90 91 77 74 97 77 49 87 49 60]
 [41 62 49 60 75 84 71 77 75 70]
 [44 83 31 84 81 36 50 81 91 52]
 [56 68 30 46 89 84 34 32 31 34]
 [88 80 68 52 63 63 82 37 41 31]]

Top 3 Student Indices:
[8 3 0]

Marks of Top 3 Students:
[[88 80 68 52 63]
 [84 71 77 75 70]
 [90 91 77 74 97]]
