# Assignment No. 14

Name:Rushabh Ratnaparkhi

College:Your College Name

Branch:Computer Engineering

Domain:AIML

GitHub Repository:

In [4]:
#Q1
import numpy as np

# a) Create array from list
list1 = [10, 20, 30, 40, 50]
array1 = np.array(list1)

# b) Create array from tuple
tuple1 = (5, 10, 15, 20)
array2 = np.array(tuple1)

# c) Create array from nested list (2D array)
nested_list = [
    [1, 2, 3],
    [4, 5, 6]
]
array3 = np.array(nested_list)

# Print arrays
print("Array from List:")
print(array1)

print("\nArray from Tuple:")
print(array2)

print("\n2D Array from Nested List:")
print(array3)

# Print data types
print("\nData Type of Array1:", array1.dtype)
print("Data Type of Array2:", array2.dtype)
print("Data Type of Array3:", array3.dtype)

Array from List:
[10 20 30 40 50]

Array from Tuple:
[ 5 10 15 20]

2D Array from Nested List:
[[1 2 3]
 [4 5 6]]

Data Type of Array1: int64
Data Type of Array2: int64
Data Type of Array3: int64
